# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'GoogleMobileVision/FaceDetector'
pod 'GoogleMobileVision/MVDataOutput'
target 'Spike' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Spike

  target 'Spike-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpikeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


